// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrovtJ3gOVX5N4XhbYnEPmk4qxDxbNmWA',
    appId: '1:1002147172300:web:93a2a443bfd19e0e69d769',
    messagingSenderId: '1002147172300',
    projectId: 'recipe-app-39d4f',
    authDomain: 'recipe-app-39d4f.firebaseapp.com',
    storageBucket: 'recipe-app-39d4f.firebasestorage.app',
    measurementId: 'G-ZHX08STKY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC98ivicJLQMmyRq_m3K92veE6_UnjOViQ',
    appId: '1:1002147172300:android:8d0b3b9c8774a6f069d769',
    messagingSenderId: '1002147172300',
    projectId: 'recipe-app-39d4f',
    storageBucket: 'recipe-app-39d4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYb3w9H9cXYJAINdhL95zqHc5abvNd-pQ',
    appId: '1:1002147172300:ios:76d115e6b8fd572069d769',
    messagingSenderId: '1002147172300',
    projectId: 'recipe-app-39d4f',
    storageBucket: 'recipe-app-39d4f.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYb3w9H9cXYJAINdhL95zqHc5abvNd-pQ',
    appId: '1:1002147172300:ios:76d115e6b8fd572069d769',
    messagingSenderId: '1002147172300',
    projectId: 'recipe-app-39d4f',
    storageBucket: 'recipe-app-39d4f.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrovtJ3gOVX5N4XhbYnEPmk4qxDxbNmWA',
    appId: '1:1002147172300:web:cc8f8d7b0833830769d769',
    messagingSenderId: '1002147172300',
    projectId: 'recipe-app-39d4f',
    authDomain: 'recipe-app-39d4f.firebaseapp.com',
    storageBucket: 'recipe-app-39d4f.firebasestorage.app',
    measurementId: 'G-0JTPWGPV1J',
  );
}
